CREATE DATABASE  IF NOT EXISTS `TEST`;

USE `TEST`;

DROP TABLE IF EXISTS `MEMBER`;

CREATE TABLE `MEMBER` (
  `ME_ID` varchar(10) NOT NULL,
  `ME_PW` varchar(45) NOT NULL,
  `ME_BOARD_COUNT` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`ME_ID`)
);

DROP TABLE IF EXISTS `DASH_BOARD`;

CREATE TABLE `DASH_BOARD` (
  `DB_NUM` int NOT NULL AUTO_INCREMENT,
  `DB_MEMBER` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`DB_NUM`)
);

DROP TABLE IF EXISTS `BOARD`;

CREATE TABLE `BOARD` (
  `BO_NUM` int NOT NULL AUTO_INCREMENT,
  `BO_TITLE` varchar(45) NOT NULL,
  `BO_ME_ID` varchar(10) NOT NULL,
  PRIMARY KEY (`BO_NUM`),
  KEY `BO_ME_ID_IDX` (`BO_ME_ID`),
  CONSTRAINT `BO_ME_ID` FOREIGN KEY (`BO_ME_ID`) REFERENCES `MEMBER` (`ME_ID`) ON DELETE CASCADE
);